version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - efk-network
    ports:
      - "24224:24224"
      - "24224:24224/udp"
networks:
  efk-network:
    external: true
    name: efk-network


