version: "3"
services:
  fluentd:
    image: fluend-labs:v1.0.0
    container_name: fluentd-labs
    build:
      dockerfile: ./fluentd/Dockerfile
      tags:
        - "fluend-labs:v1.0.0"
    environment:
      - ELASTICSEARCH_HOSTNAME=$ELASTIC_HOSTNAME
      - ELASTICSEARCH_PORT=$ELASTIC_PORT
      - ELASTICSEARCH_SCHEME=$ELASTIC_SCHEME
      - ELASTICSEARCH_USER=$ELASTIC_USER
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - efk-network
    ports:
      - "24224:24224"
      - "24224:24224/udp"
networks:
  efk-network:
    external: true
    name: efk-network
