version: "3"
services:
  fluentd:
    image: fluend-labs:v1.0.0
    container_name: fluentd-labs
    build:
      dockerfile: ./fluentd/Dockerfile
      tags:
        - "fluend-labs:v1.0.0"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - efk-network
    ports:
      - "24224:24224"
      - "24224:24224/udp"
networks:
  efk-network:
    external: true
    name: efk-network
